import type { Metadata } from 'next';
import { IsClientCtxProvider } from '@/context/IsClientContext';
import Navbar from '@/components/Navbar/Navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Makers Engineering',
  description: 'Generated by create next app',
  icons: {
    icon: '/imgs/logo/favicon.ico',
    shortcut: '/imgs/logo/favicon-32x32.png',
    apple: '/imgs/logo/apple-touch-icon.png',
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/imgs/logo/apple-touch-icon.png',
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <IsClientCtxProvider>
          <Navbar />
          {children}
        </IsClientCtxProvider>
      </body>
    </html>
  );
}
