name: Deploy Next.js App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setting up SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Ensure PM2 is installed
          npm install -g pm2

          # Define the app directory
          APP_DIR=htdocs/${{ secrets.DOMAIN }}

          # Clear the existing directory and clone the repository
          rm -rf $APP_DIR/*
          git clone [Your Repository URL] $APP_DIR
          cd $APP_DIR

          # Create .env file from GitHub secrets
          echo "NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}" > .env
          echo "NEXT_PUBLIC_SANITY_DATASET=${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          # Add other environment variables as needed

          # Pull the latest changes from the main branch
          git pull origin main

          # Install dependencies
          yarn

          # Build the app
          yarn build

          # Check if the app is already being managed by PM2
          if pm2 show ${{ secrets.APP_NAME }} > /dev/null 2>&1; then
              # Restart the existing app
              pm2 restart ${{ secrets.APP_NAME }}
          else
              # Start a new PM2 process and save the process list
              pm2 start npm --name "${{ secrets.APP_NAME }}" -- run start
              pm2 save

              # Set PM2 to startup on server boot
              pm2 startup
          fi
